import org.scalatest.prop.TableDrivenPropertyChecks

object EvaluationCases extends TableDrivenPropertyChecks {
  case class EvaluationRecord(name: String, delta: Double, priceForecastRange: Int, onlySpecificStep: Int)
  val oneOfThreePeriodsAhead = Table(
    "all four periods",
    EvaluationRecord("angi.csv", 0.03, 4, 0),
    EvaluationRecord("batra.csv", 0.03, 4, 0),
    EvaluationRecord("foxa.csv", 0.03, 4, 0),
    EvaluationRecord("fwona.csv", 0.03, 4, 0),
    EvaluationRecord("salm.csv", 0.03, 4, 0),
    EvaluationRecord("bhfap.csv", 0.03, 4, 0),
    EvaluationRecord("dpz.csv", 0.03, 4, 0),
    EvaluationRecord("hffg.csv", 0.03, 4, 0),
    EvaluationRecord("lgnd.csv", 0.03, 4, 0),
    EvaluationRecord("mtem.csv", 0.03, 4, 0),
    EvaluationRecord("nwli.csv", 0.03, 4, 0),
    EvaluationRecord("onct.csv", 0.03, 4, 0),
    EvaluationRecord("pfgc.csv", 0.03, 4, 0),
    EvaluationRecord("rzb.csv", 0.03, 4, 0),
    EvaluationRecord("very.csv", 0.03, 4, 0),
  )

  val firstPeriodAhead = Table(
    "all four periods",
    EvaluationRecord("angi.csv", 0.03, 2, 1),
    EvaluationRecord("batra.csv", 0.03, 2, 1),
    EvaluationRecord("foxa.csv", 0.03, 2, 1),
    EvaluationRecord("fwona.csv", 0.03, 2, 1),
    EvaluationRecord("salm.csv", 0.03, 2, 1),
    EvaluationRecord("bhfap.csv", 0.03, 2, 1),
    EvaluationRecord("dpz.csv", 0.03, 2, 1),
    EvaluationRecord("hffg.csv", 0.03, 2, 1),
    EvaluationRecord("lgnd.csv", 0.03, 2, 1),
    EvaluationRecord("mtem.csv", 0.03, 2, 1),
    EvaluationRecord("nwli.csv", 0.03, 2, 1),
    EvaluationRecord("onct.csv", 0.03, 2, 1),
    EvaluationRecord("pfgc.csv", 0.03, 2, 1),
    EvaluationRecord("rzb.csv", 0.03, 2, 1),
    EvaluationRecord("very.csv", 0.03, 2, 1),
  )

  val secondPeriodAhead = Table(
    "all four periods",
    EvaluationRecord("angi.csv", 0.03, 3, 2),
    EvaluationRecord("batra.csv", 0.03, 3, 2),
    EvaluationRecord("foxa.csv", 0.03, 3, 2),
    EvaluationRecord("fwona.csv", 0.03, 3, 2),
    EvaluationRecord("salm.csv", 0.03, 3, 2),
    EvaluationRecord("bhfap.csv", 0.03, 3, 2),
    EvaluationRecord("dpz.csv", 0.03, 3, 2),
    EvaluationRecord("hffg.csv", 0.03, 3, 2),
    EvaluationRecord("lgnd.csv", 0.03, 3, 2),
    EvaluationRecord("mtem.csv", 0.03, 3, 2),
    EvaluationRecord("nwli.csv", 0.03, 3, 2),
    EvaluationRecord("onct.csv", 0.03, 3, 2),
    EvaluationRecord("pfgc.csv", 0.03, 3, 2),
    EvaluationRecord("rzb.csv", 0.03, 3, 2),
    EvaluationRecord("very.csv", 0.03, 3, 2),
  )

  val thirdPeriodAhead = Table(
    "all four periods",
    EvaluationRecord("angi.csv", 0.03, 4, 3),
    EvaluationRecord("batra.csv", 0.03, 4, 3),
    EvaluationRecord("foxa.csv", 0.03, 4, 3),
    EvaluationRecord("fwona.csv", 0.03, 4, 3),
    EvaluationRecord("salm.csv", 0.03, 4, 3),
    EvaluationRecord("bhfap.csv", 0.03, 4, 3),
    EvaluationRecord("dpz.csv", 0.03, 4, 3),
    EvaluationRecord("hffg.csv", 0.03, 4, 3),
    EvaluationRecord("lgnd.csv", 0.03, 4, 3),
    EvaluationRecord("mtem.csv", 0.03, 4, 3),
    EvaluationRecord("nwli.csv", 0.03, 4, 3),
    EvaluationRecord("onct.csv", 0.03, 4, 3),
    EvaluationRecord("pfgc.csv", 0.03, 4, 3),
    EvaluationRecord("rzb.csv", 0.03, 4, 3),
    EvaluationRecord("very.csv", 0.03, 4, 3),
  )

  val oneOfThreePeriodsAheadSmallerDelta = Table(
    "all four periods",
    EvaluationRecord("angi.csv", 0.01, 4, 0),
    EvaluationRecord("batra.csv", 0.01, 4, 0),
    EvaluationRecord("foxa.csv", 0.01, 4, 0),
    EvaluationRecord("fwona.csv", 0.01, 4, 0),
    EvaluationRecord("salm.csv", 0.01, 4, 0),
    EvaluationRecord("bhfap.csv", 0.01, 4, 0),
    EvaluationRecord("dpz.csv", 0.01, 4, 0),
    EvaluationRecord("hffg.csv", 0.01, 4, 0),
    EvaluationRecord("lgnd.csv", 0.01, 4, 0),
    EvaluationRecord("mtem.csv", 0.01, 4, 0),
    EvaluationRecord("nwli.csv", 0.01, 4, 0),
    EvaluationRecord("onct.csv", 0.01, 4, 0),
    EvaluationRecord("pfgc.csv", 0.01, 4, 0),
    EvaluationRecord("rzb.csv", 0.01, 4, 0),
    EvaluationRecord("very.csv", 0.01, 4, 0),
  )

  val firstPeriodAheadSmallerDelta = Table(
    "all four periods",
    EvaluationRecord("angi.csv", 0.01, 2, 1),
    EvaluationRecord("batra.csv", 0.01, 2, 1),
    EvaluationRecord("foxa.csv", 0.01, 2, 1),
    EvaluationRecord("fwona.csv", 0.01, 2, 1),
    EvaluationRecord("salm.csv", 0.01, 2, 1),
    EvaluationRecord("bhfap.csv", 0.01, 2, 1),
    EvaluationRecord("dpz.csv", 0.01, 2, 1),
    EvaluationRecord("hffg.csv", 0.01, 2, 1),
    EvaluationRecord("lgnd.csv", 0.01, 2, 1),
    EvaluationRecord("mtem.csv", 0.01, 2, 1),
    EvaluationRecord("nwli.csv", 0.01, 2, 1),
    EvaluationRecord("onct.csv", 0.01, 2, 1),
    EvaluationRecord("pfgc.csv", 0.01, 2, 1),
    EvaluationRecord("rzb.csv", 0.01, 2, 1),
    EvaluationRecord("very.csv", 0.01, 2, 1),
  )

  val secondPeriodAheadSmallerDelta = Table(
    "all four periods",
    EvaluationRecord("angi.csv", 0.01, 3, 2),
    EvaluationRecord("batra.csv", 0.01, 3, 2),
    EvaluationRecord("foxa.csv", 0.01, 3, 2),
    EvaluationRecord("fwona.csv", 0.01, 3, 2),
    EvaluationRecord("salm.csv", 0.01, 3, 2),
    EvaluationRecord("bhfap.csv", 0.01, 3, 2),
    EvaluationRecord("dpz.csv", 0.01, 3, 2),
    EvaluationRecord("hffg.csv", 0.01, 3, 2),
    EvaluationRecord("lgnd.csv", 0.01, 3, 2),
    EvaluationRecord("mtem.csv", 0.01, 3, 2),
    EvaluationRecord("nwli.csv", 0.01, 3, 2),
    EvaluationRecord("onct.csv", 0.01, 3, 2),
    EvaluationRecord("pfgc.csv", 0.01, 3, 2),
    EvaluationRecord("rzb.csv", 0.01, 3, 2),
    EvaluationRecord("very.csv", 0.01, 3, 2),
  )

  val thirdPeriodAheadSmallerDelta = Table(
    "all four periods",
    EvaluationRecord("angi.csv", 0.01, 4, 3),
    EvaluationRecord("batra.csv", 0.01, 4, 3),
    EvaluationRecord("foxa.csv", 0.01, 4, 3),
    EvaluationRecord("fwona.csv", 0.01, 4, 3),
    EvaluationRecord("salm.csv", 0.01, 4, 3),
    EvaluationRecord("bhfap.csv", 0.01, 4, 3),
    EvaluationRecord("dpz.csv", 0.01, 4, 3),
    EvaluationRecord("hffg.csv", 0.01, 4, 3),
    EvaluationRecord("lgnd.csv", 0.01, 4, 3),
    EvaluationRecord("mtem.csv", 0.01, 4, 3),
    EvaluationRecord("nwli.csv", 0.01, 4, 3),
    EvaluationRecord("onct.csv", 0.01, 4, 3),
    EvaluationRecord("pfgc.csv", 0.01, 4, 3),
    EvaluationRecord("rzb.csv", 0.01, 4, 3),
    EvaluationRecord("very.csv", 0.01, 4, 3),
  )
}
